# Codecov Configuration
# https://docs.codecov.io/docs/codecov-yaml

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 2%  # Allow 2% drop
        if_ci_failed: error
    patch:
      default:
        target: 60%  # New code should be reasonably tested
        if_ci_failed: error

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false
