import numpy as np

CHAMPIONS_LIST = np.unique([
    "Leona",
    "Hecarim",
    "KaiSa",
    "Camille",
    "Akshan",
    "Talon",
    "Rengar",
    "Fiora",
    "Draven",
    "Pyke",
    "Cassiopeia",
    "Udyr",
    "Jinx",
    "Rell",
    "AurelionSol",
    "Seraphine",
    "Lillia",
    "Janna",
    "Jhin",
    "Kindred",
    "Sylas",
    "Zed",
    "Thresh",
    "Ivern",
    "Vayne",
    "Lulu",
    "Taliyah",
    "Viego",
    "KhaZix",
    "Zeri",
    "Nami",
    "Sett",
    "Hwei",
    "Tryndamere",
    "Shaco",
    "Taric",
    "Yasuo",
    "Evelynn",
    "Anivia",
    "Poppy",
    "Ezreal",
    "Gwen",
    "Urgot",
    "Twitch",
    "Yone",
    "Leblanc",
    "BelVeth",
    "Nunu",
    "Ashe",
    "Braum",
    "Sona",
    "KogMaw",
    "Ahri",
    "Darius",
    "RekSai",
    "Aurora",
    "MasterYi",
    "Fiddlesticks",
    "Karma",
    "Aatrox",
    "Kalista",
    "Zilean",
    "Kled",
    "Nilah",
    "TwistedFate",
    "Rammus",
    "Quinn",
    "Zac",
    "Lucian",
    "MissFortune",
    "Jax",
    "Kayn",
    "Qiyana",
    "Milio",
    "Soraka",
    "Irelia",
    "LeeSin",
    "Alistar",
    "Caitlyn",
    "Katarina",
    "Brand",
    "Akali",
    "Riven",
    "Shyvana",
    "Samira",
    "Renata",
    "Amumu",
    "Bard",
    "Skarner",
    "Lissandra",
    "Neeko",
    "Kayle",
    "Nocturne",
    "Kennen",
    "Aphelios",
    "Volibear",
    "Rakan",
    "Galio",
    "Garen",
    "JarvanIV",
    "Shen",
    "Syndra",
    "Sivir",
    "Maokai",
    "Ornn",
    "XinZhao",
    "DrMundo",
    "Swain",
    "Blitzcrank",
    "Xayah",
    "Pantheon",
    "Varus",
    "Nidalee",
    "Xerath",
    "Smolder",
    "Kassadin",
    "Warwick",
    "Karthus",
    "Vex",
    "Olaf",
    "Graves",
    "Nautilus",
    "Rumble",
    "Ekko",
    "Senna",
    "Elise",
    "Gragas",
    "Fizz",
    "Briar",
    "Teemo",
    "Jayce",
    "Naafiri",
    "Vi",
    "Vladimir",
    "Mordekaiser",
    "Gnar",
    "Yuumi",
    "Annie",
    "Trundle",
    "Illaoi",
    "ChoGath",
    "Malzahar",
    "Zyra",
    "KSante",
    "Nasus",
    "Lux",
    "Morgana",
    "Heimerdinger",
    "Sejuani",
    "Singed",
    "Ziggs",
    "Orianna",
    "TahmKench",
    "Gangplank",
    "Zoe",
    "Viktor",
    "Malphite",
    "Renekton",
    "Azir",
    "Corki",
    "Yorick",
    "MonkeyKing",
    "VelKoz",
    "Tristana",
    "Ryze",
    "Veigar",
    "Sion",
    "Diana",
    "Ambessa",
    "Mel",
    "Yunara"
])

TOP_CHAMPIONS = [
    "Aatrox",
    "Ambessa", 
    "Camille",
    "ChoGath",
    "Darius",
    "DrMundo",
    "Fiora",
    "Galio",
    "Gangplank",
    "Garen",
    "Gnar",
    "Gragas",
    "Gwen",
    "Illaoi",
    "Irelia",
    "Jax",
    "Jayce",
    "Kennen",
    "Kled",
    "KSante",
    "Malphite",
    "Mordekaiser",
    "Nasus",
    "Olaf",
    "Ornn",
    "Pantheon",
    "Poppy",
    "Quinn",
    "Renekton",
    "Riven",
    "Rumble",
    "Sett",
    "Shen",
    "Singed",
    "Sion",
    "Teemo",
    "Trundle",
    "Tryndamere",
    "Urgot",
    "Volibear",
    "MonkeyKing",
    "Yasuo",
    "Yone",
    "Yorick",
    "Zac"
]

JUNGLE_CHAMPIONS = [
    "Amumu",
    "BelVeth",
    "Briar",
    "Diana",
    "DrMundo",
    "Ekko",
    "Elise",
    "Evelynn",
    "Fiddlesticks",
    "Graves",
    "Gwen",
    "Hecarim",
    "Ivern",
    "JarvanIV",
    "Jax",
    "Karthus",
    "Kayn",
    "KhaZix",
    "Kindred",
    "LeeSin",
    "Lillia",
    "MasterYi",
    "Naafiri",
    "Nidalee",
    "Nocturne",
    "Nunu",
    "Olaf",
    "Pantheon",
    "Poppy",
    "Rammus",
    "RekSai",
    "Rengar",
    "Sejuani",
    "Shaco",
    "Shyvana",
    "Skarner",
    "Sylas",
    "Taliyah",
    "Trundle",
    "Udyr",
    "Vi",
    "Viego",
    "Volibear",
    "Warwick",
    "MonkeyKing",
    "XinZhao",
    "Zac"
]

MID_CHAMPIONS = [
    "Ahri",
    "Akali",
    "Anivia",
    "Annie",
    "AurelionSol",
    "Aurora",
    "Azir",
    "Brand",
    "Cassiopeia",
    "Corki",
    "Diana",
    "Fizz",
    "Galio",
    "Heimerdinger",
    "Hwei",
    "Kassadin",
    "Katarina",
    "Leblanc",
    "Lissandra",
    "Lux",
    "Malzahar",
    "Mel",
    "Naafiri",
    "Neeko",
    "Orianna",
    "Qiyana",
    "Ryze",
    "Sylas",
    "Syndra",
    "Taliyah",
    "Tristana",
    "TwistedFate",
    "Veigar",
    "Vex",
    "Viktor",
    "Vladimir",
    "Xerath",
    "Yasuo",
    "Yone",
    "Zed",
    "Ziggs",
    "Zoe"
]

ADC_CHAMPIONS = [
    "Aphelios",
    "Ashe",
    "Caitlyn",
    "Corki",
    "Draven",
    "Ezreal",
    "Jhin",
    "Jinx",
    "KaiSa",
    "Kalista",
    "KogMaw",
    "Lucian",
    "MissFortune",
    "Nilah",
    "Samira",
    "Senna",
    "Sivir",
    "Smolder",
    "Tristana",
    "Twitch",
    "Varus",
    "Vayne",
    "Xayah",
    "Zeri"
]

SUPPORT_CHAMPIONS = [
    "Alistar",
    "Bard",
    "Blitzcrank",
    "Brand",
    "Braum",
    "Janna",
    "Karma",
    "Leona",
    "Lulu",
    "Lux",
    "Maokai",
    "Milio",
    "Morgana",
    "Nami",
    "Nautilus",
    "Pantheon",
    "Pyke",
    "Rakan",
    "Rell",
    "Renata",
    "Senna",
    "Seraphine",
    "Sona",
    "Soraka",
    "Swain",
    "TahmKench",
    "Taric",
    "Thresh",
    "VelKoz",
    "Xerath",
    "Yuumi",
    "Zilean",
    "Zyra"
]

# Champions by role dictionary for easy access
CHAMPIONS_BY_ROLE = {
    "top": TOP_CHAMPIONS,
    "jungle": JUNGLE_CHAMPIONS,
    "mid": MID_CHAMPIONS,
    "adc": ADC_CHAMPIONS,
    "support": SUPPORT_CHAMPIONS
}

# System pools based on the new champion lists
# These represent complete champion lists by role for system use
TOP_SOLOQ_POOL = TOP_CHAMPIONS.copy()
JUNGLE_SOLOQ_POOL = JUNGLE_CHAMPIONS.copy()
MID_SOLOQ_POOL = MID_CHAMPIONS.copy()
ADC_SOLOQ_POOL = ADC_CHAMPIONS.copy()
SUPPORT_SOLOQ_POOL = SUPPORT_CHAMPIONS.copy()

# Competitive pool - balanced selection across roles
CHAMPION_POOL = [
    # Top lane meta picks
    "Aatrox", "Ambessa", "Garen", "Jax", "Malphite", "Ornn", "Shen",
    # Jungle meta picks  
    "Graves", "Hecarim", "KhaZix", "LeeSin", "Viego", "Warwick",
    # Mid lane meta picks
    "Ahri", "Akali", "Orianna", "Sylas", "Yasuo", "Zed",
    # ADC meta picks
    "Ashe", "Caitlyn", "Jinx", "KaiSa", "Lucian", "Vayne",
    # Support meta picks
    "Leona", "Nautilus", "Thresh", "Lulu", "Nami", "Morgana"
]

# Legacy compatibility - old list names
TOP_LIST = TOP_CHAMPIONS
JUNGLE_LIST = JUNGLE_CHAMPIONS
MID_LIST = MID_CHAMPIONS
ADC_LIST = ADC_CHAMPIONS
SUPPORT_LIST = SUPPORT_CHAMPIONS

SOLOQ_POOL = TOP_SOLOQ_POOL
ROLE_POOLS = CHAMPIONS_BY_ROLE

# Extended pools (same as base pools since we have complete lists now)
TOP_EXTENDED_POOL = TOP_CHAMPIONS
JUNGLE_EXTENDED_POOL = JUNGLE_CHAMPIONS
MID_EXTENDED_POOL = MID_CHAMPIONS
ADC_EXTENDED_POOL = ADC_CHAMPIONS
SUPPORT_EXTENDED_POOL = SUPPORT_CHAMPIONS

EXTENDED_POOLS = {
    "top": TOP_EXTENDED_POOL,
    "jungle": JUNGLE_EXTENDED_POOL,
    "mid": MID_EXTENDED_POOL,
    "adc": ADC_EXTENDED_POOL,
    "support": SUPPORT_EXTENDED_POOL,
    "multi-role": TOP_EXTENDED_POOL + SUPPORT_EXTENDED_POOL,
    "all-roles": TOP_EXTENDED_POOL + SUPPORT_EXTENDED_POOL + JUNGLE_EXTENDED_POOL + MID_EXTENDED_POOL + ADC_EXTENDED_POOL
}