CHAMPIONS_LIST = sorted(
    {
        "Leona",
        "Hecarim",
        "Kaisa",
        "Camille",
        "Akshan",
        "Talon",
        "Rengar",
        "Fiora",
        "Draven",
        "Pyke",
        "Cassiopeia",
        "Udyr",
        "Jinx",
        "Rell",
        "AurelionSol",
        "Seraphine",
        "Lillia",
        "Janna",
        "Jhin",
        "Kindred",
        "Sylas",
        "Zed",
        "Thresh",
        "Ivern",
        "Vayne",
        "Lulu",
        "Taliyah",
        "Viego",
        "Khazix",
        "Zeri",
        "Nami",
        "Sett",
        "Hwei",
        "Tryndamere",
        "Shaco",
        "Taric",
        "Yasuo",
        "Evelynn",
        "Anivia",
        "Poppy",
        "Ezreal",
        "Gwen",
        "Urgot",
        "Twitch",
        "Yone",
        "Leblanc",
        "Belveth",
        "Nunu",
        "Ashe",
        "Braum",
        "Sona",
        "KogMaw",
        "Ahri",
        "Darius",
        "RekSai",
        "Aurora",
        "MasterYi",
        "Fiddlesticks",
        "Karma",
        "Aatrox",
        "Kalista",
        "Zilean",
        "Kled",
        "Nilah",
        "TwistedFate",
        "Rammus",
        "Quinn",
        "Zac",
        "Lucian",
        "MissFortune",
        "Jax",
        "Kayn",
        "Qiyana",
        "Milio",
        "Soraka",
        "Irelia",
        "LeeSin",
        "Alistar",
        "Caitlyn",
        "Katarina",
        "Brand",
        "Akali",
        "Riven",
        "Shyvana",
        "Samira",
        "Renata",
        "Amumu",
        "Bard",
        "Skarner",
        "Lissandra",
        "Neeko",
        "Kayle",
        "Nocturne",
        "Kennen",
        "Aphelios",
        "Volibear",
        "Rakan",
        "Galio",
        "Garen",
        "JarvanIV",
        "Shen",
        "Syndra",
        "Sivir",
        "Maokai",
        "Ornn",
        "XinZhao",
        "DrMundo",
        "Swain",
        "Blitzcrank",
        "Xayah",
        "Pantheon",
        "Varus",
        "Nidalee",
        "Xerath",
        "Smolder",
        "Kassadin",
        "Warwick",
        "Karthus",
        "Vex",
        "Olaf",
        "Graves",
        "Nautilus",
        "Rumble",
        "Ekko",
        "Senna",
        "Elise",
        "Gragas",
        "Fizz",
        "Briar",
        "Teemo",
        "Jayce",
        "Naafiri",
        "Vi",
        "Vladimir",
        "Mordekaiser",
        "Gnar",
        "Yuumi",
        "Annie",
        "Trundle",
        "Illaoi",
        "Chogath",
        "Malzahar",
        "Zyra",
        "KSante",
        "Nasus",
        "Lux",
        "Morgana",
        "Heimerdinger",
        "Sejuani",
        "Singed",
        "Ziggs",
        "Orianna",
        "TahmKench",
        "Gangplank",
        "Zoe",
        "Viktor",
        "Malphite",
        "Renekton",
        "Azir",
        "Corki",
        "Yorick",
        "MonkeyKing",
        "Velkoz",
        "Tristana",
        "Ryze",
        "Veigar",
        "Sion",
        "Diana",
        "Ambessa",
        "Mel",
        "Yunara",
        "Zaahen",
    }
)

TOP_CHAMPIONS = [
    "Aatrox",
    "Ambessa",
    "Camille",
    "Chogath",
    "Darius",
    "DrMundo",
    "Fiora",
    "Galio",
    "Gangplank",
    "Garen",
    "Gnar",
    "Gragas",
    "Gwen",
    "Illaoi",
    "Irelia",
    "Jax",
    "Jayce",
    "Kennen",
    "Kled",
    "KSante",
    "Malphite",
    "Mordekaiser",
    "Nasus",
    "Olaf",
    "Ornn",
    "Pantheon",
    "Poppy",
    "Quinn",
    "Renekton",
    "Riven",
    "Rumble",
    "Sett",
    "Shen",
    "Singed",
    "Sion",
    "Teemo",
    "Trundle",
    "Tryndamere",
    "Urgot",
    "Volibear",
    "MonkeyKing",
    "Yasuo",
    "Yone",
    "Yorick",
    "Zac",
    "Zaahen",
]

JUNGLE_CHAMPIONS = [
    "Amumu",
    "Belveth",
    "Briar",
    "Diana",
    "DrMundo",
    "Ekko",
    "Elise",
    "Evelynn",
    "Fiddlesticks",
    "Graves",
    "Gwen",
    "Hecarim",
    "Ivern",
    "JarvanIV",
    "Jax",
    "Karthus",
    "Kayn",
    "Khazix",
    "Kindred",
    "LeeSin",
    "Lillia",
    "MasterYi",
    "Naafiri",
    "Nidalee",
    "Nocturne",
    "Nunu",
    "Olaf",
    "Pantheon",
    "Poppy",
    "Rammus",
    "RekSai",
    "Rengar",
    "Sejuani",
    "Shaco",
    "Shyvana",
    "Skarner",
    "Sylas",
    "Taliyah",
    "Trundle",
    "Udyr",
    "Vi",
    "Viego",
    "Volibear",
    "Warwick",
    "MonkeyKing",
    "XinZhao",
    "Zac",
]

MID_CHAMPIONS = [
    "Ahri",
    "Akali",
    "Anivia",
    "Annie",
    "AurelionSol",
    "Aurora",
    "Azir",
    "Brand",
    "Cassiopeia",
    "Corki",
    "Diana",
    "Fizz",
    "Galio",
    "Heimerdinger",
    "Hwei",
    "Kassadin",
    "Katarina",
    "Leblanc",
    "Lissandra",
    "Lux",
    "Malzahar",
    "Mel",
    "Naafiri",
    "Neeko",
    "Orianna",
    "Qiyana",
    "Ryze",
    "Sylas",
    "Syndra",
    "Taliyah",
    "Tristana",
    "TwistedFate",
    "Veigar",
    "Vex",
    "Viktor",
    "Vladimir",
    "Xerath",
    "Yasuo",
    "Yone",
    "Zed",
    "Ziggs",
    "Zoe",
]

ADC_CHAMPIONS = [
    "Aphelios",
    "Ashe",
    "Caitlyn",
    "Corki",
    "Draven",
    "Ezreal",
    "Jhin",
    "Jinx",
    "Kaisa",
    "Kalista",
    "KogMaw",
    "Lucian",
    "MissFortune",
    "Nilah",
    "Samira",
    "Senna",
    "Sivir",
    "Smolder",
    "Tristana",
    "Twitch",
    "Varus",
    "Vayne",
    "Xayah",
    "Yunara",
    "Zeri",
]

SUPPORT_CHAMPIONS = [
    "Alistar",
    "Bard",
    "Blitzcrank",
    "Brand",
    "Braum",
    "Janna",
    "Karma",
    "Leona",
    "Lulu",
    "Lux",
    "Maokai",
    "Milio",
    "Morgana",
    "Nami",
    "Nautilus",
    "Pantheon",
    "Pyke",
    "Rakan",
    "Rell",
    "Renata",
    "Senna",
    "Seraphine",
    "Sona",
    "Soraka",
    "Swain",
    "TahmKench",
    "Taric",
    "Thresh",
    "Velkoz",
    "Xerath",
    "Yuumi",
    "Zilean",
    "Zyra",
]

# Champions by role dictionary for easy access
CHAMPIONS_BY_ROLE = {
    "top": TOP_CHAMPIONS,
    "jungle": JUNGLE_CHAMPIONS,
    "mid": MID_CHAMPIONS,
    "adc": ADC_CHAMPIONS,
    "support": SUPPORT_CHAMPIONS,
}

# System pools based on the new champion lists
# These represent complete champion lists by role for system use
TOP_SOLOQ_POOL = TOP_CHAMPIONS.copy()
JUNGLE_SOLOQ_POOL = JUNGLE_CHAMPIONS.copy()
MID_SOLOQ_POOL = MID_CHAMPIONS.copy()
ADC_SOLOQ_POOL = ADC_CHAMPIONS.copy()
SUPPORT_SOLOQ_POOL = SUPPORT_CHAMPIONS.copy()

# Competitive pool - balanced selection across roles
CHAMPION_POOL = [
    # Top lane meta picks
    "Aatrox",
    "Ambessa",
    "Garen",
    "Jax",
    "Malphite",
    "Ornn",
    "Shen",
    # Jungle meta picks
    "Graves",
    "Hecarim",
    "Khazix",
    "LeeSin",
    "Viego",
    "Warwick",
    # Mid lane meta picks
    "Ahri",
    "Akali",
    "Orianna",
    "Sylas",
    "Yasuo",
    "Zed",
    # ADC meta picks
    "Ashe",
    "Caitlyn",
    "Jinx",
    "Kaisa",
    "Lucian",
    "Vayne",
    # Support meta picks
    "Leona",
    "Nautilus",
    "Thresh",
    "Lulu",
    "Nami",
    "Morgana",
]

EXTENDED_POOLS = {
    "top": TOP_CHAMPIONS,
    "jungle": JUNGLE_CHAMPIONS,
    "mid": MID_CHAMPIONS,
    "adc": ADC_CHAMPIONS,
    "support": SUPPORT_CHAMPIONS,
    "multi-role": TOP_CHAMPIONS + SUPPORT_CHAMPIONS,
    "all-roles": TOP_CHAMPIONS
    + SUPPORT_CHAMPIONS
    + JUNGLE_CHAMPIONS
    + MID_CHAMPIONS
    + ADC_CHAMPIONS,
}

# ========== Champion Name Normalization Functions ==========
# Déplacées vers champion_name_normalization.py (dette de code, TODO.md P4),
# réimportées ici pour ne casser aucun `from .constants import normalize_*`.

from .champion_name_normalization import (  # noqa: F401,E402
    denormalize_champion_name_from_url,
    normalize_champion_name_for_onetricks,
    normalize_champion_name_for_url,
)
